version: "2"
services:
  web:
    restart: always
    build: ./web
    ports:
      - "80:80"
    links:
      - sc

  sc:
    restart: always  
    build: ./sc
    expose:
       - "8080"
    links:
      - db
    depends_on:
      - db

  db:  
    restart: always
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    volumes_from:
      - db-data

  db-data:  
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /var/lib/postgresql/data
